pages:
  stage: deploy
  image: python:latest
  script:
  - pip install mkdocs-material mkdocstrings mkdocstrings-python
  - pip install -e .
  - cd docs
  - mkdocs build --site-dir ../public --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
