pages:
  stage: deploy
  image: python:latest
  script:
  - pip install -r docs/requirements.txt
  - pip install -e .
  - jupyter-book build docs/ --path-output build --builder html -v --config docs/_conf.yml
  - mkdir public && cp -r build/_build/html/* public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
