pages:
  stage: deploy
  image: python:latest
  script:
  - pip install -r docs/requirements.txt
  - pip install -e .
  - mkdocs build --site-dir ../public --strict --verbose
  - jupyter-book biuld docs/ --path-output ../public --builder html -v --config docs/_conf.yml
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
