image: python:3.8-buster

before_script:
  - pip install -r docs/requirements.txt

pages:
  stage: deploy
  script:
  - cd docs && mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
