[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "moea"
version = "0.0.1"
description = "A collection of multi objective optimization scenario using EnergyPLAN and MOEA."
authors = [
  { name = "Michele Urbani" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=8.37.0",
    "jupyter-book>=2.1.4",
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "notebook>=7.4.4",
    "numpy>=2.2.6",
    "pandas>=2.3.1",
    "pymoo>=0.6.1.5",
    "python-dotenv>=1.1.1",
    "typer>=0.16.0",
]

[project.scripts]
moea = "moea.cli:app"
